In [321]:
import pickle 
import os
from datetime import datetime
import pandas as pd
import numpy as np

In [322]:
model_path = r"C:\Users\ajayr\OneDrive\Docs\GitHub\Royal-Python\Bike Sharing Demand Prediction Project\Models\xgboost_regressor_r2_0_947_v1.pkl"
model = pickle.load(open(model_path, "rb"))

In [323]:
data = [[ 1.07807977,  0.22192612,  0.77468297,  1.82005277, -1.26200749,
       -0.25194272, -0.12916836, -0.17535463, -0.22754885, -5.47803337,
       -0.64744078, -0.43640293,  0.30459857,  1.74132735, -0.58152447,
       -0.57866842, -0.40630934, -0.40916536, -0.4075004 ,  2.46842407,
       -0.40081071, -0.41367015],
        [-0.65432992,  1.24504573,  0.23697162, -0.5001855 ,  0.56154562,
       -0.28664608, -0.12916836, -0.17535463, -0.22754885,  0.18254726,
        0.94701966,  0.14260346,  0.30459857, -0.57427456,  1.71961809,
       -0.57866842, -0.40630934, -0.40916536, -0.4075004 , -0.40511677,
        2.49494334, -0.41367015]]



prediction = model.predict(data)
list(prediction)

[np.float32(70.61466), np.float32(1262.1132)]

## Load SC

In [324]:
sc_dump_path =r"C:\Users\ajayr\OneDrive\Docs\GitHub\Royal-Python\Bike Sharing Demand Prediction Project\Models\scaler.pkl"

sc =pickle.load(open(sc_dump_path, "rb"))
sc

StandardScaler()

## User Input

In [325]:
date ="23/02/2026"
hour = 21
temperature = 25
humidity = 55
wind_speed = 67
visibility = 25
solar_radiation = 0.0
rainfall = 0.7
snowfall =0.2
seasons = "Winter"
holiday = "No Holiday"
functional_day = "Yes"

converting Under into Model Consumble Foramte

In [326]:
from datetime import datetime 


holiday_dic = {"Holiday":0, "No Holiday":1}
functioning_day = {"No":0, "Yes":1}

def get_string_to_datetime(date):
    dt = datetime.strptime(date, "%d/%m/%Y")
    return {"day": dt.day, "month": dt.month, "year": dt.year, "week_day": dt.strftime("%A")}

str_to_date = get_string_to_datetime(date)
str_to_date

{'day': 23, 'month': 2, 'year': 2026, 'week_day': 'Monday'}

In [327]:
u_input_list = [
    hour,
    temperature,
    humidity,
    wind_speed,
    visibility,
    solar_radiation,
    rainfall,
    snowfall,
    holiday_dic[holiday],
    functioning_day[functional_day],
    str_to_date["day"],
    str_to_date["month"],
    str_to_date["year"],
]

features_name = ['Hour', 'Temperature(°C)', 'Humidity(%)',
       'Wind speed (m/s)', 'Visibility (10m)', 'Solar Radiation (MJ/m2)',
       'Rainfall(mm)', 'Snowfall (cm)', 'Holiday', 'Functioning Day', 'Day',
       'Month', 'Year']

df_u_input =pd.DataFrame([u_input_list], columns=features_name)
df_u_input

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,Day,Month,Year
0,21,25,55,67,25,0.0,0.7,0.2,1,1,23,2,2026

In [328]:
# EX, seasons = "Winter"
def season_to_df(seasons):
    seasons_cols = ['Spring', 'Summer', 'Winter']
    seasons_data =np.zeros((1, len(seasons_cols)), dtype="int")

    df_seasons =pd.DataFrame(seasons_data, columns=seasons_cols)
    if seasons in seasons_cols:
        df_seasons[seasons]=1
    return df_seasons

df_seasons =season_to_df(seasons)
df_seasons

   Spring  Summer  Winter
0       0       0       1

In [329]:
def days_df(week_day):
    day_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',  'Saturday', 'Sunday']
    day_names_data = np.zeros((1, len(day_names)), dtype="int")

    df_days = pd.DataFrame(day_names_data, columns=day_names)
    if week_day in day_names:
        df_days[week_day] = 1
    return df_days
df_days=days_df(str_to_date["week_day"])
df_days

   Monday  Tuesday  Wednesday  Thursday  Saturday  Sunday
0       1        0          0         0         0       0

In [330]:
[ 'Hour', 'Temperature(°C)', 'Humidity(%)',
       'Wind speed (m/s)', 'Visibility (10m)', 'Solar Radiation (MJ/m2)',
       'Rainfall(mm)', 'Snowfall (cm)', 'Holiday', 'Functioning Day', 'Day',
       'Month', 'Year', 'Spring', 'Summer', 'Winter', 'Monday', 'Saturday',
       'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

['Hour',
 'Temperature(°C)',
 'Humidity(%)',
 'Wind speed (m/s)',
 'Visibility (10m)',
 'Solar Radiation (MJ/m2)',
 'Rainfall(mm)',
 'Snowfall (cm)',
 'Holiday',
 'Functioning Day',
 'Day',
 'Month',
 'Year',
 'Spring',
 'Summer',
 'Winter',
 'Monday',
 'Saturday',
 'Sunday',
 'Thursday',
 'Tuesday',
 'Wednesday']

In [331]:
df_for_pred =pd.concat([df_u_input, df_seasons, df_days], axis=1)
df_for_pred

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,...,Year,Spring,Summer,Winter,Monday,Tuesday,Wednesday,Thursday,Saturday,Sunday
0,21,25,55,67,25,0.0,0.7,0.2,1,1,...,2026,0,0,1,1,0,0,0,0,0

In [332]:
expected_columns = ['Hour', 'Temperature(°C)', 'Humidity(%)',
       'Wind speed (m/s)', 'Visibility (10m)', 'Solar Radiation (MJ/m2)',
       'Rainfall(mm)', 'Snowfall (cm)', 'Holiday', 'Functioning Day', 'Day',
       'Month', 'Year', 'Spring', 'Summer', 'Winter', 'Monday', 'Saturday',
       'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

df_for_pred = df_for_pred[expected_columns]

In [333]:
sc_data_for_pred = sc.transform(df_for_pred)
sc_data_for_pred

array([[ 1.36681471,  1.01214045, -0.15409119, 63.11301355, -2.33371591,
        -0.65681529,  0.46358031,  0.29083855,  4.39466079,  0.18254726,
         0.83312963, -1.3049125 , 29.00546301, -0.57427456, -0.58152447,
         1.72810536,  2.46117895, -0.40916536, -0.4075004 , -0.40511677,
        -0.40081071, -0.41367015]])